---
- name: turn butane into json
  #gather_facts: false
  hosts: localhost
  vars:
    my_butane_output: "{{ ignition_output_file | default('output/ign.json') }}"
    my_butane_files_dir: "{{ butane_files_dir | default('files') }}"
    my_butane_fragments: "{{ butane_fragments | default([
      './fragments/fcos-1.4.0.bu',
      './fragments/passwd.bu'
      ])}}"

  tasks:
    - name: Check if yq is installed
      ansible.builtin.command: which yq
      delegate_to: localhost
      register: yq_check
      ignore_errors: true

    - name: Install yq if not present
      delegate_to: localhost
      ansible.builtin.package:
        name: yq
        state: present
      when: yq_check.rc != 0


    - name: Download the latest Butane binary release
      delegate_to: localhost
      ansible.builtin.get_url:
        url: "https://github.com/coreos/butane/releases/latest/download/butane-{{ ansible_architecture }}-unknown-linux-gnu"
        dest: "../../tools/butane"
        mode: '0755'
    - name: combine supplied butane yaml files and ignite
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: >
          yq eval-all '. as $item ireduce ({}; . *+ $item)'
          {{ my_butane_fragments | join(" ")}}
          |
          ../../tools/butane --pretty --strict 
          -o {{ my_butane_output  }} --files-dir {{ my_butane_files_dir }}
