- name: Read and combine Butane fragments
  block:
    - name: Read Butane fragment
      ansible.builtin.import_tasks:
        file: "combine-butane/load-butane-fragment.yaml"
    - name: Combine Butane fragments
      ansible.builtin.import_tasks:
        file: "combine-butane/combine-butane.yaml"
