- block:
    - name: read butane fragment
      ansible.builtin.include_vars:
        file: "roles/butane/{{ item }}"
        name: butane_load
    - name: combine butane fragments
      ansible.builtin.set_fact:
        butane: "{{ butane | default([]) | combine(butane_load) }}"
