repos:
  - repo: https://github.com/b-/tf-pre-commit
    rev: dabb0da
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint
