repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: tofu-fmt
      - id: tofu-validate
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint
