#!/bin/bash
python3 -m venv venv
# shellcheck disable=SC1091 # because the venv activation script is not vendored
. venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -r requirements.txt