    - name: Add Butane fragment to configuration.
      ansible.builtin.set_fact:
        butane: "{{ butane | default([]) | ansible.builtin.combine(butane_add,list_merge=append_rp,recursive=true) }}"
