---
- name: Clone and provision VMs from template
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox_credentials.yaml
  vars:
    butane_fragments:
      - fragments/fcos-1.4.0.bu
      - fragments/passwd-bri.bu
      #- fragments/ucore-autorebase.bu
    butane_fragments_dir: "roles/butane"
    ignition_output_file: "roles/butane/output/ign.json"

  tasks:
    - name: Load and combine butane fragments
      with_items: "{{ butane_fragments }}"
      ansible.builtin.include_tasks:
        file: "roles/butane/tasks/combine-butane.yaml"

    - name: Generate hostname
      ansible.builtin.import_tasks:
        file: tasks/generate-hostname.yaml
      vars:
        hostname_var: "hostname_words"

    - name: Clone VM from template
      ansible.builtin.import_tasks:
        file: tasks/clone-vm.yaml

    - name: Append vmid to hostname
      ansible.builtin.import_tasks:
        file: tasks/append-to-hostname.yaml
      vars:
        hostname: "{{ hostname_words }}"
        hostname_append: "{{ vm.vmid | default(1234) }}"

#    - name: Add hostname to butane
#      ansible.builtin.set_fact:

    - name: Combine Butane fragments
      ansible.builtin.import_tasks:
        file: tasks/combine-butane.yaml
      vars:
        butane_add:
          storage:
            files:
              - path: /etc/hostname
                mode: 420 # 0644
                contents:
                  inline: "{{ hostname }}"

    - name: Print Butane configuration
      ansible.builtin.debug:
        var: butane

    - name: Build ignition files
      ansible.builtin.include_tasks:
        file: roles/butane/main.yaml

    - name: Save ignition_output to file
      ansible.builtin.copy:
        mode: 420 # 0644
        content: "{{ ignition_output.stdout }}"
        dest: "{{ ignition_output_file }}"
    - name: Upload ignition_output to sftp server
      ansible.builtin.command:
        cmd: >
          scp
            -B
            -P {{ sftp_port | default(22) }}
            -oIdentitiesOnly=true
            -i {{ sftp_key }}
            {{ ignition_output_file }}
            {{ sftp_user }}@{{ sftp_host }}:snippets/{{ vm.vmid }}.ign
      changed_when: true

    - name: Set VM cicustom to Ignition file
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user | default(null) }}"
        api_token_id: "{{ proxmox_token_id | default(omit) }}"
        api_token_secret: "{{ proxmox_token | default(omit)}}"
        api_password: "{{ proxmox_password | default(omit) }}"
        api_host: "{{ proxmox_host | default('localhost') }}"
        api_port: "{{ proxmox_port | default(8006)  }}"
        node: "{{ proxmox_node | default(omit) }}"
        cicustom: "user={{ proxmox_snippet_storage }}:snippets/{{ vm.vmid }}.ign"
        name: "{{ hostname }}"
        update: true
        vmid: "{{ vm.vmid }}"
        pool: "{{ proxmox_pool | default(omit) }}"
        # full: true
        state: present
      register: vmupdate
