---
- name: Clone and provision VMs from template
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox_credentials.yaml
  vars:
    butane_fragments:
      - fragments/fcos-1.4.0.bu
      - fragments/passwd-bri.bu
      #- fragments/ucore-autorebase.bu
    butane_fragments_dir: "roles/butane"
    ignition_output_file: "roles/butane/output/ign.json"

  tasks:
    - name: Load and combine butane fragments
      with_items: "{{ butane_fragments }}"
      ansible.builtin.include_tasks: # cannot be import_tasks
        file: "roles/butane/tasks/combine-butane.yaml"

    - name: Generate hostname
      ansible.builtin.import_tasks:
        file: tasks/generate-hostname.yaml
      vars:
        hostname_var: "hostname_words"

    - name: Clone VM from template
      ansible.builtin.import_tasks:
        file: tasks/clone-vm.yaml

    - name: Append vmid to hostname
      ansible.builtin.import_tasks:
        file: tasks/append-to-hostname.yaml
      vars:
        hostname: "{{ hostname_words }}"
        hostname_append: "{{ vm.vmid | default(1234) }}"

    - name: Add hostname to Butane configuration
      ansible.builtin.import_tasks:
        file: tasks/add-hostname-to-butane.yaml

    - name: Print Butane configuration
      ansible.builtin.debug:
        var: butane

    - name: Build ignition files
      ansible.builtin.import_tasks:
        file: roles/butane/main.yaml

    - name: Save ignition_output to file
      ansible.builtin.copy:
        mode: 420 # 0644
        content: "{{ ignition_output.stdout }}"
        dest: "{{ ignition_output_file }}"

    - name: Upload ignition_output to sftp server
      ansible.builtin.import_tasks:
        file: tasks/upload-ignition.yaml

    - name: Set VM cicustom to Ignition file
      ansible.builtin.import_tasks:
        file: tasks/set-cicustom.yaml
