---
- name: Clone and provision VMs from template
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox_credentials.yaml

  tasks:
    - name: Clone VM from template
      community.general.proxmox_kvm:
        # api_user: "{{ proxmox_user }}"
        # api_password: "{{ proxmox_password }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token: "{{ proxmox_token }}"
        api_host: "{{ proxmox_host }}"
        api_port: "{{ proxmox_port }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_vm }}"
        cicustom: "user=pmxcfs:snippets/komodo-core.json"
        name: "{{ item }}"
        vmid: "{{ 100 + ansible_index }}"
        pool: "{{ proxmox_pool }}"
        full: true
        state: present
      loop: "{{ groups['target_vms'] }}"
      loop_control:
        index_var: ansible_index
